site_name: Informatique en CPGE
site_description: Cours d'informatique en MP2I et ITC  (lycée Leconte de Lisle)
site_author: Fabrice NATIVEL

docs_dir: docs

nav:
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/home.svg' width=16px height=16px>&thinsp; Accueil" : index.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Cours de MP2I" :
      - "Chapitres" :
        - "Index" : mp2i/progression.md
        - "C0-Notions d'architecture et de systèmes" : mp2i/systemes.md
        - "C1-Premiers pas en langage C" : mp2i/introC.md
        - "C2-Spécifications et tests" : mp2i/validation.md
        - "C3-Pointeurs et types structurés": mp2i/pointeurs.md
        - "C4-Arithmétique des ordinateurs": mp2i/arithmetique.md
        - "C5-Récursivité": mp2i/recursivite.md
        - "C6-OCaml : aspects fonctionnels" : mp2i/introOCaml.md
        - "C7-Terminaison, correction, complexité": mp2i/terminaison.md
        - "C8-Structures de données linéaires": mp2i/sl.md
        - "C9-Ocaml : aspects impératifs" : mp2i/OCamlimp.md
        - "C10-Tableau associatif, hachage": mp2i/hash.md
        - "C11-Introduction aux bases de données" : mp2i/introbd.md
        - "C12-Arbres binaires" : mp2i/arbres.md
        - "C13-Force brute, retour sur trace" : mp2i/forcebrute.md
        - "C14-Syntaxe des formules logiques" :  mp2i/logique.md"
        - "C15-Graphes"  : mp2i/graphes.md"
        - "C16-Décomposition en sous problèmes" :  mp2i/decomposition.md,
        - "C17-Induction" : /mp2i/induction.md,
        - "C18-Modèle entité-association, jointures" : mp2i/jointures.md
        - "C19-Algorithmes des textes"  : mp2i/textes.md
        - "C20-Calcul propositionnel" : mp2i/propositionel.md
        - "C21-Algorithmes des graphes" : mp2i/algographes.md
      - "TP notés" : mp2i/progression/#tp-notes
      - "Devoirs maison" : mp2i/progression/#devoirs-maison
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Cours d'ITC" :
      - "Index" : itc/progression.md
      - "C0-Un peu de Python" : itc/revisions.md
      - "C1-Introduction aux bases de données" : itc/introbd.md
      - "C2-Programmation dynamique" : itc/progdyn.md
      - "C3-Jointures" : itc/jointures.md
      - "C4-k plus proches voisins, k-moyennes" : itc/knn.md
      - "C5-Algorithme pour l'étude des jeux" : itc/algojeux.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/check.svg' width=16px height=16px>&thinsp; Evaluations" :
    - evaluations.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/file-badge-16.svg' width=16px height=16px>&thinsp; Programmes" :
    - programmes.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/links.svg' width=16px height=16px>&thinsp; Liens" :
    - liens.md

theme:
  name: material
  custom_dir: overrides
  language : fr 
  features:
    - content.code.copy #copie et annotation du code
    - content.code.annotate 
    - content.tabs.link # Lien volets
    - navigation.tabs # barre de navigation dans l'en-tête
    - navigation.tabs.sticky



extra_css:
  - stylesheets/fenarius.css


markdown_extensions:
  - pymdownx.arithmatex: #Mathjax
      generic: true
  - admonition  # Admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - "docs/mp2i/files/"
        - "docs/itc/files/"
        - "docs/mp2i/Evaluations/TP/"
        - "docs/mp2i/Evaluations/DM/"
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html
  - pymdownx.tabbed:    # Possibilité de créer des volets
      alternate_style: true 
  - pymdownx.superfences: # Mermaid pour les graphes
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - macros
  - kroki

# Pour mathjax
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascript/check.js

