# À modifier avec le nom et la description du site
site_name: "Cours d'informatique en CPGE"
site_description: Cours de la filière MP2I et cours d'Informatique de tronc commun (Lycée Leconte de Lisle - Académie de la Réunion)
site_url : 'https://fabricenativel.github.io/cpge-info'

# Éventuellement à modifier avec votre thème de couleurs
theme:
    custom_dir: overrides
    favicon: assets/images/favicon.png
    icon:
      logo: fontawesome/solid/user-graduate
    name: pyodide-mkdocs-theme
    palette:
      primary: custom

    # La palette de couleur est maintenant intégrée par défaut au thème.
    # Si vous souhaitez en changer, vous pouvez redéclarer la section entière
    # et vos réglages prendront le pas sur les valeurs par défaut.
    # Mêmes choses pour la langue et la suppression des google-fonts (non RGPD).
    #font: false                     # RGPD ; pas de fonte Google
    #language: fr                    # français
    #palette:                        # Palettes de couleurs jour/nuit
      #- media: "(prefers-color-scheme: light)"
        #scheme: default
        #primary: indigo
        #accent: indigo
        #toggle:
            #icon: material/weather-sunny
            #name: Passer au mode nuit
      #- media: "(prefers-color-scheme: dark)"
        #scheme: slate
        #primary: black
        #accent: green
        #toggle:
            #icon: material/weather-night
            #name: Passer au mode jour
    features:
    - content.code.copy #copie et annotation du code
    - content.code.annotate 
    - content.tabs.link # Lien volets
    - navigation.tabs # barre de navigation dans l'en-tête
    - navigation.tabs.sticky
    - navigation.expand

docs_dir: docs


markdown_extensions:
    - md_in_html
    - abbr
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight:           # Coloration syntaxique du code
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets: 
        base_path:
        - "docs/mp2i/files/"
        - "docs/itc/files/"
        - "docs/mp2i/Evaluations/TP/"
        - "docs/mp2i/Evaluations/DM/DM1"
        - "docs/mp2i/Evaluations/DM/"
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:              # Volets glissants.  === "Mon volet"
        alternate_style: true
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji: # Émojis  :boom:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: 2
        toc_depth: 3


plugins:
  - search
  - tags:
      tags_file: tags.md
  - pyodide_macros:
      # Vous pouvez ajouter ici tout réglage que vous auriez ajouté concernant les macros:
      on_error_fail: true     # Il est conseillé d'ajouter celui-ci si vous ne l'utilisez pas.
      build:
        python_libs:
          - turtle
        tab_to_spaces: 4

# En remplacement de mkdocs-exclude. Tous les fichiers correspondant aux patterns indiqués seront
# exclu du site final et donc également de l'indexation de la recherche.
# Nota: ne pas mettre de commentaires dans ces lignes !
exclude_docs: |
    **/*_REM.md
    **/*.py

extra_javascript:
  - javascript/check.js
  - path: "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js"

extra_css:
  #- xtra/stylesheets/ajustements.css  # ajustements
  - stylesheets/fenarius.css


nav:
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/home.svg' width=16px height=16px>&thinsp; Accueil" : index.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Cours de MP2I" :
      - "Index des chapitres" : mp2i/progression.md
      - "Semestre 1" :
        - "C0-Notions d'architecture et de systèmes" : mp2i/systemes.md
        - "C1-Premiers pas en langage C" : mp2i/introC.md
        - "C2-Spécifications et tests" : mp2i/validation.md
        - "C3-Pointeurs et types structurés": mp2i/pointeurs.md
        - "C4-Arithmétique des ordinateurs": mp2i/arithmetique.md
        - "C5-Récursivité": mp2i/recursivite.md
        - "C6-OCaml : aspects fonctionnels" : mp2i/introOCaml.md
        - "C7-Terminaison, correction, complexité": mp2i/terminaison.md
        - "C8-Structures de données linéaires": mp2i/sl.md
        - "C9-Ocaml : aspects impératifs" : mp2i/OCamlimp.md
      - "Semestre 2":
        - "C10-Tableau associatif, hachage": mp2i/hash.md
        - "C11-Introduction aux bases de données" : mp2i/introbd.md
        - "C12-Arbres binaires" : mp2i/arbres.md
        - "C13-Force brute, retour sur trace" : mp2i/forcebrute.md
        - "C14-Induction" :  mp2i/induction.md
        - "C15-Décomposition en sous problèmes" :  mp2i/decomposition.md
        - "C16-Logique" : mp2i/logique.md
        - "C17-Graphes"  : mp2i/graphes.md
        - "C18-Modèle entité-association" : mp2i/mea.md
        - "C19-Algorithmes des textes"  : mp2i/textes.md
        - "C20-Algorithmes des graphes" : mp2i/algographes.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Cours d'ITC" :
      - "Index" : itc/progression.md
      - "Semestre 1":
        - "C0-Faire le point" : itc/point.md
        - "C1-Bases de Python" : itc/bases.md
        - "C2-Listes" : itc/listes.md
        - "C3-Fichiers" : itc/fichiers.md
        - "C4-Discipline de programmation": itc/discipline.md
        - "C5-Dictionnaires": itc/dictionnaires.md
        - "C6-Récursivité": itc/recursivite.md
        - "C7-Algorithmes gloutons": itc/gloutons.md
        - "C8-Tris": itc/tris.md
      - "Semestre 2":
        - "C9-Spécifications et tests" : itc/tests.md
        - "C10-Représentation des entiers" : itc/entiers.md
        - "C11-Terminaison et corrections" : itc/terminaison.md
        - "C12-Graphes" : itc/graphes.md
        - "C13-Complexité" : itc/complexite.md
        - "C14-Représentation des flottants" : itc/flottants.md
        - "C15-Plus courts chemins dans un graphe" : itc/parcours.m
      - "Semestre 3":
        - "C16-Un peu de Python" : itc/revisions.md
        - "C17-Introduction aux bases de données" : itc/introbd.md
        - "C18-Programmation dynamique" : itc/progdyn.md
        - "C19-Jointures" : itc/jointures.md
        - "C20-k plus proches voisins, k-moyennes" : itc/knn.md
        - "C21-Algorithme pour l'étude des jeux" : itc/algojeux.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/check.svg' width=16px height=16px>&thinsp; Evaluations" :
    - evaluations.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/file-badge-16.svg' width=16px height=16px>&thinsp; Programmes" :
    - programmes.md
  - "<img src='https://fabricenativel.github.io/cpge-info/icones/links.svg' width=16px height=16px>&thinsp; Liens" :
    - liens.md

